config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :relationships, only: [:create, :destroy, :show]
  resources :fronts, only: [:index, :show]
  resources :graphs
  resources :persons

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :blogs do
    resources :loves, only: [:create, :destroy]
    resources :supports, only: [:create]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

    belongs_to :user
    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :supports, dependent: :destroy
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/front.rb
class Front < ApplicationRecord
end

app/models/graph.rb
class Graph < ApplicationRecord

    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/person.rb
class Person < ApplicationRecord 

    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy

    mount_uploader :image, ImageUploader
    
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

        

          has_many :tweets, dependent: :destroy
          validates :name, presence: true
          validates :profile, length: { maximum: 100 }

          has_many :likes, dependent: :destroy
          has_many :liked_tweets, through: :likes, source: :tweet
          has_many :comments, dependent: :destroy

          has_many :relationships
          has_many :followings, through: :relationships, source: :follow
          has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
          has_many :followers, through: :reverse_of_relationships, source: :user

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy

          mount_uploader :image, ImageUploader

          has_many :blogs, dependent: :destroy
          has_many :loves, dependent: :destroy
          has_many :loved_blogs, through: :loves, source: :blog
          has_many :supports, dependent: :destroy

          has_many :graphs

          has_many :persons



          

          def already_liked?(tweet)
            self.likes.exists?(tweet_id: tweet.id)
          end

        def follow(other_user)
          unless self == other_user
              self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

        def already_loved?(blog)
          self.loves.exists?(blog_id: blog.id)
        end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :authenticate_user!

    def index
        @blogs = Blog.all.order(created_at: :desc)
        @my_blogs = @blogs.select { |blog| blog.user_id == current_user.id } 
    end
    
    def new
        @blog = Blog.new
    end
    
    
    def create
        blog = Blog.new(blog_parameter)
        blog.user_id = current_user.id
        
        if blog.save
            redirect_to :action => "index"
        else 
            redirect_to :action => "new"
        end
    end

    def show
        @blog = Blog.find(params[:id])
        @supports = @blog.supports
        @support = Support.new
    end
    
    def destroy
        blog = Blog.find(params[:id])
        blog.destroy
        redirect_to blogs_path
    end
    
    def edit
        @blog = Blog.find(params[:id])
        @user = User.find(params[:id])

    end
    
    def update
        blog = Blog.find(params[:id])
        if blog.update(blog_parameter)
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    
    private
    
    def blog_parameter
        params.require(:blog).permit(:name, :part, :training, :about, :start_time)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span class="description">Home Trainee</span></a></h1>
</div>

<div class="blog-edit">
    <h2>筋トレ記録編集</h2>
    <%= form_for @blog do |f| %>

    <div class="field">
        <%= f.label :部位, class:"blog-label blog-part" %>
        <%= f.select :part,
    [["腹筋", "腹筋"],
    ["肩", "肩"],
    ["背中", "背中"]], include_blank: "選択して下さい" %>
    </div>
    <div class="field">
        <%= f.label :種目, class:"blog-label" %>
        <%= f.text_field :training, :size => 30, class:"blog-field" %>
    </div>
    <div class="field">
        <%= f.label :感想, class:"blog-label" %>
        <%= f.text_field :about, :size => 30, class:"blog-field" %>
    </div>
    <div class="time">
        <%= f.label :トレーニング日, class:"blog-label" %>
        <%= f.datetime_select :start_time, class:"blog-field" %>
    </div>
    <div class="submit">
        <%= f.submit "編集する", class:"submit-text" %>
        <% end %>
    </div>
</div>

app/views/blogs/index.html.erb
<link rel="stylesheet" href="stylesheets/blogs.css">

<div class="header-page" data-turbolinks="false">
<h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span class="description">Home Trainee</span></a></h1>
</div>



<div class="blogs-container">
  <div class="blog-index-left">
    <li><i class="far fa-comment-alt"></i>筋トレ記録一覧</li>
    <li><i class="far fa-comment-alt"></i><%= link_to "おすすめ投稿一覧", tweets_path %></li>
    <li><i class="far fa-user"></i><%= link_to "おうちトレーニー", users_path %></li>
    <li><i class="far fa-address-card"></i><%= link_to "マイプロフィール", user_path(current_user.id) %></li>
    <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
    <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
  </div>

  <div class="blog-index-center">
    <% @blogs.each do |t| %>
    <div class="blog">
      <ul class="top-blog">
      <% if t.user.image? %>
      <li><img src='<%= t.user.image %>' class="icon", size: "50x50" alt="ユーザーアイコン"></li>
      <% else %>
      <li><image src="/assets/8.png" class="icon", size: "50x50" alt="ユーザーアイコン" %></li>
          <% end %>
        <li><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
        <li class="content"><%= t.start_time.strftime("%Y-%m-%d %H:%M") %></li>
      </ul>
      <ul class="detail-blog">
        <li class="title">筋トレ部位</li>
        <li class="content"><%= t.part %></li>
      </ul>
      <ul class="detail-blog">
        <li class="title">トレーニング名</li>
        <li class="content"><%= t.training %></li>
      </ul>
      <ul class="detail-blog">
        <li class="content"><%= t.about %></li>
      </ul>

      <div class="bottom-blog">
        <% if user_signed_in? %>
        <% if current_user.already_loved?(t) %>
        <%= link_to blog_love_path(id: t.id, blog_id: t.id), method: :delete do %>
        <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.loves.count %></span>
        <% end %>
        <% else %>
        <%= link_to blog_loves_path(id: t.id, blog_id: t.id), method: :post do %>
        <i class="fas fa-heart"></i><%= t.loves.count %>
        <% end %>
        <% end %>
        <% else %>
        <i class="fas fa-heart"></i><%= t.loves.count %>
        <% end %>
        <ul>
          <% if user_signed_in? && current_user.id == t.user_id %>
          <li><%= link_to edit_blog_path(t.id) do   %>
            <i class="far fa-edit"></i>
            <% end %>
          </li>
          <li><%= link_to blog_path(t.id), method: :delete do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>

    <% end %>
  </div>
  <div class="blog-index-right">
    <h2>あなたの最近の筋トレ記録</h2>
    <% @my_blogs.each do |t| %>
    <div class="blog-self">
      <ul class="blog-self-box1">
      <% if t.user.image? %>
      <li><img src='<%= t.user.image %>' class="icon", size: "50x50" alt="ユーザーアイコン"></li>
      <% else %>
      <li><image src="/assets/8.png" class="icon", size: "50x50" alt="ユーザーアイコン" %></li>
          <% end %>
        <li><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
      </ul>
      <div class="blog-detail">
        <li><%= t.start_time.strftime("%Y-%m-%d") %></li>
        <li><%= t.part %></li>
        <li><%= t.training %></li>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<link rel="stylesheet" href="stylesheets/blogs.css">

<div class="header-blog-new">
    <ul>
        <li><%= link_to "マイページ", front_path(id: current_user) %></li>
        <li><i class="far fa-comment-alt"></i>今日の筋トレを記録</li>
        <li><%= link_to "みんなの今日の筋トレ記録をみる", blogs_path %></li>
    </ul>
</div>
<div class="blogs-container">
    <div class="blog-new-left">
        <li><i class="fas fa-home"></i><%= link_to "マイページ", front_path(id: current_user) %></li> 
        <li><i class="far fa-comment-alt"></i>今日の筋トレを記録</li>
        <li><i class="far fa-comment-alt"></i><%= link_to "筋トレ記録一覧", blogs_path %></li>
        <li><i class="far fa-comment-dots"></i><%= link_to "おすすめ投稿", new_tweet_path %></li>
        <li><i class="far fa-comment-alt"></i><%= link_to "おすすめ投稿一覧", tweets_path %></li>
        <li><i class="far fa-user"></i><%= link_to "おうちトレーニー", users_path %></li>
        <li><i class="far fa-address-card"></i><%= link_to "マイプロフィール", user_path(current_user.id) %></li>
        <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
        <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
    </div>
    <div class="blog-new-center">
        <%= form_with(model: @blog, local: true) do |f| %>
        <div class="field">
            <%= f.label :部位 %>
            <%= f.select :part,
            [["腹筋", "腹筋"],
            ["肩", "肩"]], include_blank: "選択して下さい" %>
        </div>

        <div class="field">
            <%= f.label :種目 %>
            <%= f.text_field :training, :size => 30 %>
        </div>

        <div class="field">
            <%= f.label :感想 %>
            <%= f.text_field :about, :size => 30 %>
        </div>

        <div class="time">
            <%= f.label :トレーニング日 %>
            <%= f.datetime_select :start_time %>
        </div>


        <div class="submit">
            <%= f.submit %>
        </div>
        <% end %>
    </div>
    <div class="blog-new-right">

    </div>
</div>

app/views/blogs/show.html.erb
<div class="blog">
<p>
    <strong>ユーザー名</strong>
    <%= @blog.user.name %>
</p>

<p>
    <strong>トレーニング</strong>
    <%= @blog.training %>
</p>

<p>
    <strong>日付</strong>
    <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
    <strong>感想</strong>
    <%= @blog.about %>
</p>

<% if user_signed_in? %>
<% if current_user.already_loved?(@blog) %>
    <%= link_to blog_love_path(@blog), method: :delete do %>
        <i class="fas fa-heart red-heart"></i><span class="red-count"><%= @blog.loves.count %></span>
    <% end %>
<% else %>
    <%= link_to blog_loves_path(@blog), method: :post do %>
        <i class="fas fa-heart"></i><%= @blog.loves.count %>
    <% end %>
<% end %>
<% else %>
<i class="fas fa-heart"></i><%= @blog.loves.count %>
<% end %>

</div>
<h2>いいねしたユーザー</h2>
<% @blog.loved_users.each do |user| %>
    <li><%= user.email %></li>
<% end %>

<div class="support-wrapper">
<p>コメント一覧</p>
<% @supports.each do |c| %>
<div>
    <%= c.user.email unless c.user.blank? %>
    <br>
    <%= c.content %>
  </div>
    <br>
<% end %>

<% if user_signed_in? %>
  <%= form_with(model: [@blog, @support], local: true) do |f| %>
    <%= f.text_area :content %>
    <%= button_tag type: "submit" do %>
      <i class="far fa-comments"></i> コメントする
    <% end %>
  <% end %>
<% end %>
</div>  

<%= link_to '記録を編集する', edit_blog_path(@blog) %> |
<%= link_to '筋トレカレンダーに戻る', blogs_path %>