config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :relationships, only: [:create, :destroy, :show]
  resources :fronts, only: [:index, :show]
  resources :graphs
  resources :persons

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :blogs do
    resources :loves, only: [:create, :destroy]
    resources :supports, only: [:create]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

    belongs_to :user
    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :supports, dependent: :destroy
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/front.rb
class Front < ApplicationRecord
end

app/models/graph.rb
class Graph < ApplicationRecord

    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/person.rb
class Person < ApplicationRecord 

    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy

    mount_uploader :image, ImageUploader
    
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

        

          has_many :tweets, dependent: :destroy
          validates :name, presence: true
          validates :profile, length: { maximum: 100 }

          has_many :likes, dependent: :destroy
          has_many :liked_tweets, through: :likes, source: :tweet
          has_many :comments, dependent: :destroy

          has_many :relationships
          has_many :followings, through: :relationships, source: :follow
          has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
          has_many :followers, through: :reverse_of_relationships, source: :user

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy

          mount_uploader :image, ImageUploader

          has_many :blogs, dependent: :destroy
          has_many :loves, dependent: :destroy
          has_many :loved_blogs, through: :loves, source: :blog
          has_many :supports, dependent: :destroy

          has_many :graphs

          has_many :persons



          

          def already_liked?(tweet)
            self.likes.exists?(tweet_id: tweet.id)
          end

        def follow(other_user)
          unless self == other_user
              self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

        def already_loved?(blog)
          self.loves.exists?(blog_id: blog.id)
        end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

    def index
        @graphs = Graph.all
        @result = Graph.pluck(:weigh_on, :weight)
    end

    def show

    end

    def new
        @graph = Graph.new
    end

    def create
        graph = Graph.new(graph_parameter)
        graph.user_id = current_user.id
        
        if graph.save
            redirect_to controller: :fronts, action: :show, id: current_user.id
        else 
            redirect_to :action => "new"
        end
    end

    def destroy
        graph = Graph.find(params[:id])
        graph.destroy
        redirect_to graphs_path
    end
    
    def edit
        @graph = Graph.find(params[:id])
    end
    
    def update
        graph = Graph.find(params[:id])
        if graph.update(graph_parameter)
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def graph_parameter
        params.require(:graph).permit(:name, :weight, :weigh_on)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphs/edit.html.erb
<h1>体重管理の編集</h1>
<%= form_for @graph do |f| %>

<div class="field">
    <%= f.label :体重%>
    <%= f.text_field :weight %>
</div>

<div class="time">
<%= f.label :今日の日付%>
<%= f.datetime_select :weigh_on %>
</div>
<%= f.submit "編集する" %>
<% end %>

app/views/graphs/index.html.erb
<% @graphs.each do |t| %>
    <tr>
      <td><a href="/users/<%= t.user.id %>"><%= t.user.name %></a><td>
      <td><%= t.weight %></td>
      <td><%= t.weigh_on.strftime("%Y-%m-%d ") %></td>
      <td><%= link_to '編集する', edit_graph_path(t.id) %></td>
      <td><%= link_to '削除する',graph_path(t.id), method: :delete, data: { confirm: '体重管理をやめますか?' } %></td>
    </tr>
  <% end %>

<%= line_chart @result, xtitle: "日付", ytitle: "体重",max:100 %>

<%= link_to "マイページへ", front_path(id: current_user) %>

app/views/graphs/new.html.erb
<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span
                class="description">Home Trainee</span></a></h1>
</div>

<div class="graph-new">
    <h2>体重管理</h2>
    <%= form_with(model: @graph, local: true) do |f| %>

    <div class="time">
        <%= f.label :今日の日付, class:"graph-label blog-time" %>
        <%= f.date_select :weigh_on %>
    </div>

    <div class="field">
        <%= f.label :体重, class:"graph-label" %>
        <%= f.text_field :weight, :size => 30, class:"graph-field" %>
    </div>
    <div class="submit">
        <%= f.submit "体重管理する", class:"submit-text" %>
    </div>
    <% end %>
</div>