config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :relationships, only: [:create, :destroy, :show]
  resources :fronts, only: [:index, :show]
  resources :graphs
  resources :persons

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :blogs do
    resources :loves, only: [:create, :destroy]
    resources :supports, only: [:create]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

    belongs_to :user
    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :supports, dependent: :destroy
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/front.rb
class Front < ApplicationRecord
end

app/models/graph.rb
class Graph < ApplicationRecord

    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/person.rb
class Person < ApplicationRecord 

    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy

    mount_uploader :image, ImageUploader
    
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

        

          has_many :tweets, dependent: :destroy
          validates :name, presence: true
          validates :profile, length: { maximum: 100 }

          has_many :likes, dependent: :destroy
          has_many :liked_tweets, through: :likes, source: :tweet
          has_many :comments, dependent: :destroy

          has_many :relationships
          has_many :followings, through: :relationships, source: :follow
          has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
          has_many :followers, through: :reverse_of_relationships, source: :user

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy

          mount_uploader :image, ImageUploader

          has_many :blogs, dependent: :destroy
          has_many :loves, dependent: :destroy
          has_many :loved_blogs, through: :loves, source: :blog
          has_many :supports, dependent: :destroy

          has_many :graphs

          has_many :persons



          

          def already_liked?(tweet)
            self.likes.exists?(tweet_id: tweet.id)
          end

        def follow(other_user)
          unless self == other_user
              self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

        def already_loved?(blog)
          self.loves.exists?(blog_id: blog.id)
        end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    before_action :authenticate_user!

    def index
        @tweets =Tweet.all.order(created_at: :desc) 
        @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(10).pluck(:tweet_id))
        @tweet = Tweet.new
    end

    def new 
        @tweet = Tweet.new
        @tweets =Tweet.all.order(created_at: :desc) 
        @my_tweets = @tweets.select { |tweet| tweet.user_id == current_user.id } 
    end

    def create
        tweet = Tweet.new(tweet_params)
        @tweet = Tweet.new(tweet_params)
        url = params[:tweet][:youtube_url]
        url = url.last(11)
        @tweet.youtube_url = url

        tweet.user_id = current_user.id
        
        if tweet.save
            redirect_to :action => "index"
        else 
            redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end


    private
    def tweet_params
        params.require(:tweet).permit(:name, :part, :training, :about, :image, :youtube_url,:title)
    end

   

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/edit.html.erb
<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span class="description">Home Trainee</span></a></h1>

</div>
    <div class="tweet-edit">
        <h2>おすすめ投稿編集</h2>
        <%= form_for @tweet do |f| %>
        <div class="field">
            <%= f.label :タイトル, class:"tweet-label" %>
            <%= f.text_field :title, :size => 30, class:"tweet-field" %>
        </div>

        <div class="field">
            <%= f.label :部位, class:"tweet-label tweet-part" %>
            <%= f.select :part,
    [["腹筋", "腹筋"],
    ["肩", "肩"],
    ["背中", "背中"]], include_blank: "選択して下さい" %>

        </div>
        <div class="field">
            <%= f.label :種目, class:"tweet-label" %>
            <%= f.text_field :training, :size => 30, class:"tweet-field" %>
        </div>
        <div class="field">
            <%= f.label :内容, class:"tweet-label" %>
            <%= f.text_field :about, :size => 30, class:"tweet-field" %>
        </div>

        <div class="field">
            <%= f.label :画像, class:"tweet-label" %>
            <%= f.file_field :image %>
        </div>
        <div class="field">
            <%= f.label :YouTube, class:"tweet-label" %>
            <%= f.url_field :youtube_url, :size => 100, class:"tweet-field"  %>
        </div>
        <div class="submit">
            <%= f.submit "編集する", class:"submit-text" %>
            <% end %>
        </div>
    </div>

app/views/tweets/index.html.erb
<link rel="stylesheet" href="stylesheets/tweets.css">
<%= javascript_pack_tag 'script' %>


<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span
                class="description">Home Trainee</span></a></h1>
</div>

<div class="modal1" id="modal1">
    <div class="tweet-new-center">
        <div class="modal1-top">
            <h2>おすすめ投稿</h2>
            <a class="modal1-close" id="modal1-close">×</a>
        </div>
        <%= form_for @tweet do |f| %>
        <div class="field">
            <%= f.label :タイトル, class:"tweet-label" %>
            <%= f.text_field :title, :size => 100, :placeholder => "タイトルを入力してください。", class:"tweet-field" %>
        </div>
        <div class="field">
            <%= f.label :部位, class:"tweet-label tweet-part" %>
            <%= f.select :part,
        [["腹筋", "腹筋"],
        ["肩", "肩"],
        ["背中", "背中"]], include_blank: "選択して下さい" %>

        </div>
        <div class="field">
            <%= f.label :種目, class:"tweet-label" %>
            <%= f.text_field :training, :size => 100, :placeholder => "種目を入力してください。", class:"tweet-field"  %>
        </div>
        <div class="field">
            <%= f.label :内容, class:"tweet-label" %>
            <%= f.text_field :about, :size => 100, :placeholder => "内容を入力してください。", class:"tweet-field" %>
        </div>
        <div class="field">
            <%= f.label :画像, class:"tweet-label" %>
            <%= f.file_field :image %>
        </div>
        <div class="field">
            <%= f.label :YouTube, class:"tweet-label" %>
            <%= f.url_field :youtube_url, :size => 100, :placeholder => "YouTubeのURLを入力してください。", class:"tweet-field"  %>
        </div>
        <div class="submit">
            <%= f.submit "投稿する", class:"submit-text" %>
        </div>
        <% end %>
    </div>
</div>

<div class="mask1" id="mask1"></div>



<div class="tweets-container">
    <div class="tweet-left">
        <li><i class="far fa-comment-alt"></i>おすすめ投稿一覧</li>
        <li><i class="far fa-comment-alt"></i><%= link_to "筋トレ記録一覧", blogs_path %></li>
        <li><i class="far fa-user"></i><%= link_to "おうちトレーニー", users_path %></li>
        <li><i class="far fa-address-card"></i><%= link_to "プロフィール", user_path(current_user.id) %></li>
        <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
        <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
    </div>
    <div class="tweet-center">
        <% @tweets.each do |t| %>
        <div class="tweet">
            <ul class="top-tweet">
                <% if t.user.image? %>
                <li><img src='<%= t.user.image %>' class="icon", size: "50x50" alt="ユーザーアイコン"></li>
                <% else %>
                <li><image src="/assets/8.png" class="icon", size: "50x50" alt="ユーザーアイコン" %></li>
                    <% end %>
                    <li><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
                    <li><%= t.created_at %></li>
            </ul>
            <ul class="detail-tweet">
                <li class="title">おすすめ内容</li>
                <li class="content"><%= t.title %></li>
            </ul>
            <ul class="detail-tweet">
                <li class="title">筋トレ部位</li>
                <li class="content"><%= t.part %></li>
            </ul>
            <ul class="detail-tweet">
                <li class="title">トレーニング名</li>
                <li class="content"><%= t.training %></li>
            </ul>
            <ul class="detail-tweet">
                <li class="title">コメント</li>
                <li class="content"><%= t.about %></li>
            </ul>
            <div class="imagevideo">
                <%= image_tag t.image_url, size: "250x200" if t.image? %>
                <iframe width="300" height="200" src="https://www.youtube.com/embed/
                <%=t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; 
                encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div class="bottom-tweet">
                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.likes.count %></span>
                <% end %>
                <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
                <% end %>
                <% else %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
                <ul>
 
                    <% if user_signed_in? && current_user.id == t.user_id %>
                    <li><%= link_to edit_tweet_path(t.id) do   %>
                        <i class="far fa-edit"></i>
                        <% end %>
                    </li>
                    <li><%= link_to tweet_path(t.id), method: :delete do %>
                        <i class="fas fa-trash"></i>
                        <% end %>
                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
        <% end %>
    </div>


    <div class="tweet-right">
        <h2>いいね数ランキング</h2>
        <% @all_ranks.each do |f| %>
        <% @tweets.each do |t| %>
        <div class="rank-tweet">
            <ul class="rank-tweet-box1">
                <% if t.user.image? %>
                <li><img src='<%= t.user.image %>' class="icon", size: "50x50" alt="ユーザーアイコン"></li>
                <% else %>
                <li><image src="/assets/8.png" class="icon", size: "50x50" alt="ユーザーアイコン" %></li>
                    <% end %>
                <li><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
            </ul>
            <ul class="rank-tweet-box2">
                <li><%= t.title %></li>
                <li><%= t.part %></li>
                <li><%= t.training %></li>
            </ul>
            <ul class="rank-tweet-box3">
                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.likes.count %></span>
                <% end %>
                <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
                <% end %>
                <% else %>
                <li><i class="fas fa-heart"></i><%= t.likes.count %></li>
                <% end %>

                <% if user_signed_in? && current_user.id == t.user_id %>
                <li><%= link_to edit_tweet_path(t.id) do   %>
                    <i class="far fa-edit"></i>
                    <% end %>
                </li>
                <li><%= link_to tweet_path(t.id), method: :delete do %>
                    <i class="fas fa-trash"></i>
                    <% end %>
                </li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

<%= javascript_pack_tag 'script' %>

app/views/tweets/new.html.erb
<link rel="stylesheet" href="stylesheets/tweets.css">



<div class="header-tweet-new">
    <ul>
        <li><%= link_to "マイページ", front_path(id: current_user) %></li>
        <li><i class="far fa-comment-alt"></i>おすすめ投稿</li>
        <li><%= link_to "おすすめ投稿一覧", tweets_path %></li>
    </ul>
</div>

<div class="tweets-container">
    <div class="tweet-left">
        <li><i class="fas fa-home"></i><%= link_to "マイページ", front_path(id: current_user), class:"function" %></li>
        <li><i class="far fa-comment-alt"></i>おすすめ投稿</li>
        <li><i class="far fa-comment-dots"></i><%= link_to "今日の筋トレを記録", new_blog_path %> </li>
        <li><i class="far fa-comment-alt"></i><%= link_to "筋トレ記録一覧", blogs_path %></li>
        <li><i class="far fa-user"></i><%= link_to "おうちトレーニー", users_path %></li>
        <li><i class="far fa-address-card"></i><%= link_to "マイプロフィール", user_path(current_user.id) %></li>
        <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
        <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
    </div>
    <div class="tweet-new-center">
        <h2>おすすめ投稿</h2>
        <%= form_for @tweet do |f| %>
        <div class="field">
            <%= f.label :タイトル, class:"tweet-label" %>
            <%= f.text_field :title, :size => 100, :placeholder => "タイトルを入力してください。", class:"tweet-field" %>
        </div>
        <div class="field">
            <%= f.label :部位, class:"tweet-label tweet-part" %>
            <%= f.select :part,
        [["腹筋", "腹筋"],
        ["肩", "肩"],
        ["背中", "背中"]], include_blank: "選択して下さい" %>

        </div>
        <div class="field">
            <%= f.label :種目, class:"tweet-label" %>
            <%= f.text_field :training, :size => 100, :placeholder => "種目を入力してください。", class:"tweet-field"  %>
        </div>
        <div class="field">
            <%= f.label :内容, class:"tweet-label" %>
            <%= f.text_field :about, :size => 100, :placeholder => "内容を入力してください。", class:"tweet-field" %>
        </div>
        <div class="field">
            <%= f.label :画像, class:"tweet-label" %>
            <%= f.file_field :image %>
        </div>
        <div class="field">
            <%= f.label :YouTube, class:"tweet-label" %>
            <%= f.url_field :youtube_url, :size => 100, :placeholder => "YouTubeのURLを入力してください。", class:"tweet-field"  %>
        </div>
        <div class="submit">
            <%= f.submit "投稿する", class:"submit-text" %>
        </div>
        <% end %>
    </div>
    <div class="tweet-new-right">
        <% @my_tweets.each do |t| %>
        <div class="tweet-self">
            <ul class="tweet-self-box1">
                <li><%= image_tag t.user.image_url, size: "50x50" if t.user.image? %> </li>
                <li><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
            </ul>
            <div class="tweet-self-box2">
                <li><%= t.title %></li>
                <li><%= t.part %></li>
                <li><%= t.training %></li>
            </div>
            <ul class="tweet-self-box3">
                <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.likes.count %></span>
                <% end %>
                <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
                <% end %>
                <% else %>
                <li><i class="fas fa-heart"></i><%= t.likes.count %></li>
                <% end %>

                <% if user_signed_in? && current_user.id == t.user_id %>
                <li><%= link_to edit_tweet_path(t.id) do   %>
                    <i class="far fa-edit"></i>
                    <% end %>
                </li>
                <li><%= link_to tweet_path(t.id), method: :delete do %>
                    <i class="fas fa-trash"></i>
                    <% end %>
                </li>
                <% end %>
            </ul>
        </div>
        <% end %>
    </div>
</div>

app/views/tweets/show.html.erb
<link rel="stylesheet" href="stylesheets/tweets.css">



<div class="header-page" data-turbolinks="false">
<h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span class="description">Home Trainee</span></a></h1>

</div>


<div class="tweets-container">

  <div class="tweet-show-center">
    <h1>おすすめ投稿詳細</h1>
    <div class="tweet">
      <ul class="top-tweet">
        <li><%= image_tag @tweet.user.image_url, size: "50x50" if @tweet.user.image? %> </li>
        <li><a href="/users/<%= @tweet.user.id %>"><%= @tweet.user.name %></a></li>
        <li><%= @tweet.created_at %></li>
      </ul>
      <ul class="detail-tweet">
        <li class="title">おすすめ内容</li>
        <li class="content"><%= @tweet.title %></li>
      </ul>
      <ul class="detail-tweet">
        <li class="title">筋トレ部位</li>
        <li class="content"><%= @tweet.part %></li>
      </ul>
      <ul class="detail-tweet">
        <li class="title">トレーニング名</li>
        <li class="content"><%= @tweet.training %></li>
      </ul>
      <ul class="detail-tweet">
        <li class="title">コメント</li>
        <li class="content"><%= @tweet.about %></li>
      </ul>
      <div class="imagevideo">
        <%= image_tag @tweet.image_url, size: "250x200" if @tweet.image? %>
        <iframe width="300" height="200" src="https://www.youtube.com/embed/
      <%= @tweet.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; 
      encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div class="good">

        <% if user_signed_in? %>
        <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fas fa-heart red-heart"></i><span class="red-count"><%= @tweet.likes.count %></span>
        <% end %>
        <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
        <% end %>
        <% else %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
        <div class="good-user">
          <h2>いいねしたユーザー</h2>
          <% @tweet.liked_users.each do |t| %>
          <li><%= image_tag t.image_url, size: "50x50" if t.image? %> </li>
          <li><%= t.name %></li>
          <% end %>
        </div>
      </div>

      <div class="comment-wrapper">
        <p>コメント一覧</p>
        <% @comments.each do |c| %>
        <div>
          <%= c.user.email unless c.user.blank? %>
          <br>
          <%= c.content %>
        </div>
        <br>
        <% end %>

        <% if user_signed_in? %>
        <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>