config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :relationships, only: [:create, :destroy, :show]
  resources :fronts, only: [:index, :show]
  resources :graphs
  resources :persons

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :blogs do
    resources :loves, only: [:create, :destroy]
    resources :supports, only: [:create]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

    belongs_to :user
    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :supports, dependent: :destroy
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/front.rb
class Front < ApplicationRecord
end

app/models/graph.rb
class Graph < ApplicationRecord

    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/person.rb
class Person < ApplicationRecord 

    belongs_to :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy

    mount_uploader :image, ImageUploader
    
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

        

          has_many :tweets, dependent: :destroy
          validates :name, presence: true
          validates :profile, length: { maximum: 100 }

          has_many :likes, dependent: :destroy
          has_many :liked_tweets, through: :likes, source: :tweet
          has_many :comments, dependent: :destroy

          has_many :relationships
          has_many :followings, through: :relationships, source: :follow
          has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
          has_many :followers, through: :reverse_of_relationships, source: :user

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy

          mount_uploader :image, ImageUploader

          has_many :blogs, dependent: :destroy
          has_many :loves, dependent: :destroy
          has_many :loved_blogs, through: :loves, source: :blog
          has_many :supports, dependent: :destroy

          has_many :graphs

          has_many :persons



          

          def already_liked?(tweet)
            self.likes.exists?(tweet_id: tweet.id)
          end

        def follow(other_user)
          unless self == other_user
              self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

        def already_loved?(blog)
          self.loves.exists?(blog_id: blog.id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]

    def index
      if params[:search] == nil
        @users= User.all
      elsif params[:search] == ''
        @users= User.all
      else
        @users = User.where("name LIKE ? ",'%' + params[:search] + '%')
      end
    end

    def show
        @user = User.find(params[:id])
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
        if @user.id == current_user.id
        else
          @currentUserEntry.each do |cu|
            @userEntry.each do |u|
              if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
              end
            end
          end
          if @isRoom
          else
            @room = Room.new
            @entry = Entry.new
          end
        end
    end

    def following
      @user = User.find(params[:id])
    end
    def followers
      @user = User.find(params[:id])
    end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span
                class="description">Home Trainee</span></a></h1>
</div>


<div class="back-profile">
    <li><%= link_to "プロフィールに戻る", user_path(@user.id) %></li>
</div>

<div class="followers-box">
    <h1><%= @user.name %>さんのフォロワー</h1>
    <% @user.followers.each do |t| %>
    <div class="followers-user">
        <% if t.image? %>
        <li><img src='<%= t.image %>' class="icon" , size: "50x50" alt="ユーザーアイコン"></li>
        <% else %>
        <li>
            <image src="/assets/8.png" class="icon" , size: "50x50" alt="ユーザーアイコン" %>
        </li>
        <% end %>
        <li class="followers-name"><a href="/users/<%= t.id %>"><%= t.name %></a></li>
    </div>
    <% end %>
</div>

app/views/users/following.html.erb
<div class="header-page" data-turbolinks="false">
    <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span
                class="description">Home Trainee</span></a></h1>
</div>

<div class="back-profile">
    <li><%= link_to "プロフィールに戻る", user_path(@user.id) %></li>
</div>

<div class="following-box">
    <h1><%= @user.name %>さんのフォロー</h1>

    <% @user.followings.each do |t| %>
    <div class="following-user">

        <% if t.image? %>
        <li><img src='<%= t.image %>' class="icon" , size: "50x50" alt="ユーザーアイコン"></li>
        <% else %>
        <li>
            <image src="/assets/8.png" class="icon" , size: "50x50" alt="ユーザーアイコン" %>
        </li>
        <% end %>
        <li class="following-name"><a href="/users/<%= t.id %>"><%= t.name %></a></li>
    </div>
    <% end %>
</div>

app/views/users/index.html.erb
<link rel="stylesheet" href="stylesheets/users.css">



<div class="header-page" data-turbolinks="false">
<h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span class="description">Home Trainee</span></a></h1>
</div>

<div class="users-container">
  <div class="user-left">
    <li><i class="far fa-user"></i>おうちトレーニー</li>
    <li><i class="far fa-comment-alt"></i><%= link_to "おすすめ投稿一覧", tweets_path %></li>
    <li><i class="far fa-comment-alt"></i><%= link_to "筋トレ記録一覧", blogs_path %></li>
    <li><i class="far fa-address-card"></i><%= link_to "マイプロフィール", user_path(current_user.id) %></li>
    <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
    <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
  </div>

  <div class="user-index-center">
    <div class="search-wrapper">
      <% if user_signed_in? %>
      <h3>おうちトレーニーを探す</h3>
      <div class="search-box">
        <%= form_tag({controller:"users",action:"index"}, method: :get) do %>
        <%= text_field_tag :search, "", class: 'search-field', placeholder:"検索..." %>
        <%= submit_tag '検索する', class:"search-button"  %>
        <% end %>
      </div>
    </div>
    <div class="user-wrapper">
      <% @users.each do |u| %>
      <div class="user-self-wrapper">
      <% if u.image? %>
      <li><img src='<%= u.image %>' class="icon", size: "50x50" alt="ユーザーアイコン"></li>
      <% else %>
      <li><image src="/assets/8.png" class="icon", size: "50x50" alt="ユーザーアイコン" %></li>
          <% end %>
        <p><a href="/users/<%= u.id %>"><%= u.name %></a></p>
      </div>
      <% end %>
      <% else %>
      <%= link_to "ユーザーを登録する", new_user_registration_path %>
      <br>
      <%= link_to "ログインする", new_user_session_path %>
      <% end %>
    </div>
  </div>
  <div class="user-index-right">

  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<div class="user-shared-login">
  <%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
  <% end %>
</div>

<div class="user-shared-signup">
  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウント登録", new_registration_path(resource_name) %><br />
  <% end %>
</div>



<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
<%- resource_class.omniauth_providers.each do |provider| %>
<%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
<% end %>
<% end %>

app/views/users/show.html.erb
<link rel="stylesheet" href="stylesheets/users.css">

<div class="header-page" data-turbolinks="false">
  <h1><a href="/fronts/<%= current_user.id %>"><span class="maintitle">The Strongest</span><span
        class="description">Home Trainee</span></a></h1>
</div>

<div class="users-container">



  <ul class="user-left">
    <li><i class="far fa-address-card"></i>プロフィール</li>
    <li><i class="far fa-comment-alt"></i><%= link_to "おすすめ投稿一覧", tweets_path %></li>
    <li><i class="far fa-comment-alt"></i><%= link_to "筋トレ記録一覧", blogs_path %></li>
    <li><i class="far fa-user"></i><%= link_to "おうちトレーニー", users_path %></li>
    <li><i class="far fa-edit"></i><%= link_to "体重管理", new_graph_path %></li>
    <li><i class="fas fa-dumbbell"></i><%= link_to "体型診断", new_person_path %></li>
  </ul>

  <div class="user-show-center">
    <div class="top-detail">
      <p><%= image_tag @user.image_url %></p>
      <p class="show-name"><%= @user.name %></p>
    </div>
    <div class="balloon1">
      <% if @user.profile? %>
      <p><%= @user.profile %></p>
      <% else %>
      <p>よろしくお願いいたします。</p>
      <% end %>

    </div>

    <ul class="fo">
      <li><a href="/users/<%= @user.id %>/following"><%= @user.followings.count %>フォロー中</a></li>
      <li><a href="/users/<%= @user.id %>/followers"><%= @user.followers.count %>フォロワー</a></li>
    </ul>

    <% if @user.id == current_user.id %>

    <% else %>
    <% if @isRoom == true %>
    <p><a class="go-chat" href="/rooms/<%= @roomId %>">チャットへ</a>
      <% else %>
      <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
      <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", :class=>"start-chat" %>
      <% end %>
      <% end %>
      <% end %>
      <%= render "relationships/follow_button", user: @user %>

      <% if current_user.id == @user.id %>
      <div class="user-edit">
        <%= link_to "編集する", edit_user_registration_path, class:"user-edit-text" %>
      </div>
      <% end %>
  </div>


  <div class="user-show-right">
    <h2><%= @user.name %>さんの筋トレ記録</h2>
    <div class="user-blog">
      <% @user.blogs.each do |t| %>
      <div class="user-blog-self">
        <ul class="user-blog-self-box1">
          <% if t.user.image? %>
          <li><img src='<%= t.user.image %>' class="icon" , size: "50x50" alt="ユーザーアイコン"></li>
          <% else %>
          <li>
            <image src="/assets/8.png" class="icon" , size: "50x50" alt="ユーザーアイコン" %>
          </li>
          <% end %>
          <li><%= t.user.name %></li>
          <li><%= t.created_at %></li>
        </ul>
        <ul class="user-blog-self-box2">
          <li><%= t.part %></li>
          <li><%= t.training %></li>
          <li><%= t.about %></li>
        </ul>
        <ul class="user-blog-self-box3">
          <% if user_signed_in? %>
          <% if current_user.already_loved?(t) %>
          <%= link_to blog_love_path(id: t.id, blog_id: t.id), method: :delete do %>
          <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.loves.count %></span>
          <% end %>
          <% else %>
          <%= link_to blog_loves_path(id: t.id, blog_id: t.id), method: :post do %>
          <i class="fas fa-heart"></i><%= t.loves.count %>
          <% end %>
          <% end %>
          <% else %>
          <li><i class="fas fa-heart"></i><%= t.loves.count %></li>
          <% end %>

          <% if user_signed_in? && current_user.id == t.user_id %>
          <li><%= link_to edit_blog_path(t.id) do   %>
            <i class="far fa-edit"></i>
            <% end %>
          </li>
          <li><%= link_to blog_path(t.id), method: :delete do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>

    <h2><%= @user.name %>さんがいいねした筋トレ記録</h2>
    <div class="user-blog">
      <% @user.loved_blogs.each do |t| %>
      <div class="user-blog-self">
        <ul class="user-blog-self-box1">
          <% if t.user.image? %>
          <li><img src='<%= t.user.image %>' class="icon" , size: "50x50" alt="ユーザーアイコン"></li>
          <% else %>
          <li>
            <image src="/assets/8.png" class="icon" , size: "50x50" alt="ユーザーアイコン" %>
          </li>
          <% end %>
          <li><%= t.user.name %></li>
          <li><%= t.created_at %></li>
        </ul>
        <ul class="user-blog-self-box2">
          <li><%= t.part %></li>
          <li><%= t.training %></li>
          <li><%= t.about %></li>
        </ul>
        <ul class="user-blog-self-box3">
          <% if user_signed_in? %>
          <% if current_user.already_loved?(t) %>
          <%= link_to blog_love_path(id: t.id, blog_id: t.id), method: :delete do %>
          <i class="fas fa-heart red-heart"></i><span class="red-count"><%= t.loves.count %></span>
          <% end %>
          <% else %>
          <%= link_to blog_loves_path(id: t.id, blog_id: t.id), method: :post do %>
          <i class="fas fa-heart"></i><%= t.loves.count %>
          <% end %>
          <% end %>
          <% else %>
          <li><i class="fas fa-heart"></i><%= t.loves.count %></li>
          <% end %>

          <% if user_signed_in? && current_user.id == t.user_id %>
          <li><%= link_to edit_blog_path(t.id) do   %>
            <i class="far fa-edit"></i>
            <% end %>
          </li>
          <li><%= link_to blog_path(t.id), method: :delete do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>